#!/bin/env bash
##
CURRENT_REPO_PATH=$(pwd)
PROJECT_NAME=$(basename "$CURRENT_REPO_PATH")
ROOT_WORKSPACE="/home/git/gitea-workspace/"
PROJECT_WORKSPACE="${ROOT_WORKSPACE}/${PROJECT_NAME}"
TESTS_WRAPPER="./tests/run_all_units.sh"
#######
#--
_cleanup() {
  rm -rf "${PROJECT_WORKSPACE}"
}

#-- prepare
mkdir -p "$PROJECT_WORKSPACE"

trap _cleanup EXIT

#--
while read -r _ newrev _
do
    git archive "${newrev}" | tar -x -C "${PROJECT_WORKSPACE}"

    pushd "${PROJECT_WORKSPACE}"
    [[ ! -x ${TESTS_WRAPPER} ]] && continue;

    echo -e "\n\e[92m[CI]\e[39m Preparing to run tests for \e[92m${newrev}\e[39m ...\n"

    if ! ${TESTS_WRAPPER}; then
        echo -e "\n\e[92m[CI]\e[39m\e[91m Failure while running tests on rev ${newrev} - push denied.\e[39m\n\e[92m[CI]\e[39m Run tests locally using \e[93m${TESTS_WRAPPER}\e[39m and confirm they pass before pushing."
        exit 1
    fi
done
echo -e "\n"
#-- OK
exit 0
